// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN237Hua0h_6LDEi3owLHI65Wf7JbplRs',
    appId: '1:166419229335:web:9e7171ffaf2b2c22a197d2',
    messagingSenderId: '166419229335',
    projectId: 'bmi-calculator-38b1a',
    authDomain: 'bmi-calculator-38b1a.firebaseapp.com',
    storageBucket: 'bmi-calculator-38b1a.firebasestorage.app',
    measurementId: 'G-GQ4R61KXZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAq0ieoFTfLE1k5z5DJO2Fy9b3IeI5teQ',
    appId: '1:166419229335:android:78f0e403519669e5a197d2',
    messagingSenderId: '166419229335',
    projectId: 'bmi-calculator-38b1a',
    storageBucket: 'bmi-calculator-38b1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVv2oHzDseTHtsot9__NCTD8A3nC_gfb8',
    appId: '1:166419229335:ios:e56ba90e7b4586cfa197d2',
    messagingSenderId: '166419229335',
    projectId: 'bmi-calculator-38b1a',
    storageBucket: 'bmi-calculator-38b1a.firebasestorage.app',
    iosBundleId: 'com.example.dartProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVv2oHzDseTHtsot9__NCTD8A3nC_gfb8',
    appId: '1:166419229335:ios:e56ba90e7b4586cfa197d2',
    messagingSenderId: '166419229335',
    projectId: 'bmi-calculator-38b1a',
    storageBucket: 'bmi-calculator-38b1a.firebasestorage.app',
    iosBundleId: 'com.example.dartProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN237Hua0h_6LDEi3owLHI65Wf7JbplRs',
    appId: '1:166419229335:web:3b9c6a3ae84be64ca197d2',
    messagingSenderId: '166419229335',
    projectId: 'bmi-calculator-38b1a',
    authDomain: 'bmi-calculator-38b1a.firebaseapp.com',
    storageBucket: 'bmi-calculator-38b1a.firebasestorage.app',
    measurementId: 'G-9YPGCY77HJ',
  );
}